### ISSUE TITLE
Crashing when Leaf Blocks are in Range

### ISSUE THREAD

**Issue by Nallek** [TehNut/Torcherino#1]
As the title suggests, there's a fatal crash whenever a Torcherino is in range of and is ticking a leaf block.

**Comment by TehNut** [comment]
Log?

**Comment by Nallek** [comment]
Seems like it only happens when the leaf block is decayable
[Uploading crash-2016-05-22_19.54.03-server.txt…]()

**Comment by Nallek** [comment]
Seems like it crashes when the leaf block is decayable
[crash-2016-05-22_19.54.03-server.txt](https://github.com/TehNut/Torcherino/files/276529/crash-2016-05-22_19.54.03-server.txt)
